version: 1

update_configs:
    - package_manager: javascript
      directory: /
      update_schedule: live

      default_reviewers:
          - whizark

      default_assignees:
          - whizark

      allowed_updates:
          - match:
              update_type: security
              dependency_type: indirect

      commit_message:
          prefix: build
